### ISSUE TITLE
Staging ENV fails

### ISSUE THREAD

**Issue by exocode** [assembler/attachinary#80]
Hi Milovan,
I got this error when I try to deploy on STAGING environment

`rake aborted!
       Must supply cloud_name in tag or in configuration
       (in /tmp/build_963b09e2-9363-4e08-b60f-56f44f98464d/app/assets/stylesheets/application.scss)`

ENV Variables:

```
CLOUDINARY_API_KEY:      123456789
CLOUDINARY_API_SECRET:   abcdefghijklmnopqrsuvwxyz
CLOUDINARY_CLOUD_NAME:   abc123456789
CLOUDINARY_URL:          cloudinary://123456789:abcdefghijklmnopqrsuvwxyz@abc123456789
RACK_ENV:                staging
RAILS_ENV:               staging
```

My cloudinary.yml looks like this:

```
development:
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false    
production:
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
staging:
  <<: *production
test:
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
```

How can I resolve that?

many, many thanks
